### ISSUE TITLE
Detach this repository from jfclere's fork

### ISSUE THREAD

**Issue by csutherl** [picketbox/tomcat-vault#38]
This repository is marked as a fork of the outdated original repository (jfclere/tomcat-vault). I recall a conversation with @jfclere about this and wanting to 'fix' that problem. In order to remove that reference you can open a ticket with Github support to switch it to 'normal mode'. See excerpt from [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork):

'To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."'

Alternatively it seems that you can delete the repo, recreate it, and push your local copy up but switching the mode is probably safer :)

**Comment by jfclere** [comment]
I am on it ;-)

**Comment by jfclere** [comment]
Done
